version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: arun
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=arun
      - DB_PASS=password
    depends_on:
      - db
  kong:
    image: avinashupadhya99/kong-event-pub:1.0.0-1
    environment:
      KONG_DECLARATIVE_CONFIG: /opt/conf/kong.yml
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: 'off'
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PLUGINS: kong-event-pub
      KONG_LOG_LEVEL: 'debug'
    ports:
      - "8000:8000/tcp"
      - "127.0.0.1:8001:8001/tcp"
    volumes:
      - ./kong:/opt/conf/
    depends_on:
      - app
volumes:
  postgres_data:

